######################## default configuration ####################

theme = "twenty-twenty-hugo"

# post pagination
pagination.pagerSize = "6"

# post excerpt
summaryLength = "10"

# disable language
disableLanguages = [] # disable language from here

############################## Output ###############################

[outputs]
home = ["HTML", "RSS", "JSON"]
