# --------------------------
# English language
# --------------------------

[it]
languageName = "It"
languageCode = "it-IT"
contentDir = "content"
weight = 1


[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content"
weight = 2
