
############################## navigation ###############################


# main menu
[[main]]
name = "Home"
URL = "/"
weight = 1


[[main]]
name = "News"
URL = "news/"
weight = 2

[[main]]
name = "Eventi"
URL = "eventi/"
weight = 3

[[main]]
name = "Archivio"
URL = "archivio/"
weight = 4


[[main]]
name = "Iscriviti alla newsletter"
URL = "newsletter/"
weight = 5



[[main]]
name = "Chi siamo"
URL = "chi-siamo/"
weight = 6




# only desktop menu
[[desktop]]
name = "News"
URL = "news/"
weight = 1
