title = 'Ciao Capitello'
baseURL = "https://www.painfulstaff.com/capitello/"


[params]
description = "This is meta description"
author = "begnolas"



# banner
[params.banner]
heading = "Dove vorresti essere pensato? <br />Su una piroga, in giro"
image = "images/capo.png"






# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

#################### default parameters ################################


# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2
content = "Questo sito utilizza i cookie. Continuando a navigare, acconsenti al loro utilizzo."
button = "Accetto"





# blog
[params.news]
heading = "Uno spazio dove ricordare Lele e proseguire il suo impegno."


# call to action
[params.call_to_action]
enable = true
title = "Vuoi ricevere aggiornamenti su come stiamo portando avanti i progetti in ricordo di Lele? <br />Lascia la tua email, ti scriveremo solo per cose davvero importanti."
content = ""
button_label = "Contattaci"
button_url = "contatti/"




# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item]]
image = "images/gallery_01.png"

[[params.gallery.gallery_item]]
image = "images/gallery_02.png"


[[params.gallery.gallery_item]]
image = "images/gallery_03.png"


[[params.gallery.gallery_item]]
image = "images/gallery_04.png"


# footer
[params.footer]
title = "About"
content = "Uno spazio dove ricordare Lele e proseguire il suo impegno."
copyright = "Copyright &copy; 2021 a hugo theme by themefisher ported from WordPress Twenty Twenty."





[params.social]
#yelp = "#"
#facebook = "#"
#twitter = "#"
#instagram = "#"
email = "ciaocapitello@gmail.com"
#linkedin = "#"
whatsapp = "+393402411153"



