title = 'Ciao Capitello'
baseURL = "https://www.painfulstaff.com/capitello/"


[params]
description = "This is meta description"
author = "Begna"



# banner
[params.banner]
heading = "Dove vorresti essere pensato? <br />Su una piroga, in giro"
image = "images/capo.png"






# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

#################### default parameters ################################


# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = true
expire_days = 2
content = "Questo sito utilizza i cookie. Continuando a navigare, acconsenti al loro utilizzo."
button = "Accetto"





# blog
[params.news]
heading = "Una frase di apertura che racconti il senso di questo spazio (“Un luogo per ricordare, condividere e continuare il suo sorriso”)."



# call to action
[params.call_to_action]
enable = true
title = "Contattaci per maggiori informazioni"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contattaci"
button_url = "contatti/"




# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"





# footer
[params.footer]
title = "About This Site"
content = "This may be a good place to introduce yourself and your site or include some credits."
copyright = "Copyright &copy; 2021 a hugo theme by themefisher ported from WordPress Twenty Twenty."





[params.social]
#yelp = "#"
#facebook = "#"
#twitter = "#"
#instagram = "#"
email = "ciaocapitello@gmail.com"
#linkedin = "#"
whatsapp = "+393402411153"